#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  5 11:56:37 2019

@author: rockchar
"""

#-------------------------- FOR LOOPS -------------------------

list_1 = [1,2,3,4,5,6,7,8,9,10]

for x in list_1:
    print(x)
    
    
    
my_string = "hello world"

for letter in my_string:
    if letter == "w":
        print("W found")
        break
    
#----------- List comprehension using for loops -------------
        
my_list = []
for letter in my_string:
    my_list.append(letter)

print(my_list)

my_list2 = [letter for letter in my_string]
print(my_list2)

my_list3 = [x for x in range(1,11)]
print(my_list3)

#squaring a number in place in a list
my_list4 = [x**2 for x in range(1,11)]
print(my_list4)

#print all the odd numbers in the range 
myList = [x for x in range(1,11) if x%2 != 0]
print(myList)

#farenheit to celcius conversion in place

list_celcius = [0,32,65,41,100,72]
list_farenheit = [(9/5*celcius + 32) for celcius in list_celcius ]
print(list_celcius)
print(list_farenheit)

#print odd and even numbers 
list_num = [1,2,3,4,5,6,7,8]
list_odd = ["ODD "if num%2!=0  else num for num in list_num ]
print(list_odd)


# multiplying two lists in place. Each number in list1 is multiplied by each 
#number in list2
list1 = [2,4,6]
list2 = [100,200,300]
list3 =[]
for x in list1:
    for y in list2:
        list3.append(x*y)

#the same operation as above just that it is done in place
print( [x*y for x in list1 for y in list2] )
print(list3)

print()


#------------- Ranges and steps -----------------------------
print(list_1[1:11:2])#slice(start:stop[:step])

#------------- Slice Object ---------------------------------
list_5 = ["String1","String2","String3"]
result = slice(1,2)
print(list_5[result])

